name: 02 - Workflow Events

on:
  # push:
  # pull_request:
  schedule:
    - cron: '0 3 */4 * *'  # Запускать каждый 4-й день в 3:00 UTC
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by ${{ github.event_name }}"
