name: 04 - Using Actions

on:
  # push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print folders
        run: ls

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Install Dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app

      - name: Run Unit test
        run: npm run test
        working-directory: 04-using-actions/react-app
