name: 04 - Using Actions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code  # Space after '-'
        uses: actions/checkout@v4

      - name: Print folders
        run: ls  # Fixed 'ls-something'
